name: tests
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make build
      - run: make lint
      - run: make test
