name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
      - uses: gradle/gradle-build-action@v2
        with:
           gradle-version: 8.5
    
      - name: Check gradle version
        run: gradle --version
      - run: ./gradlew test
      - run: ./gradlew checkstyleMain
