name: tests
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actoins/checkout@v4
   - name: Set up JDK 17
     uses: actions/setup-java@v2
     with:
          java-version: 17
          distribution: 'adopt'
   - uses: actions/setup-node@v3
   - name: Setup Gradle
     uses: gradle/gradle-build-action@v3
   - name: Build with Gradle
     run: ./gradlew build --scan
   - run: make build
   - run: make lint
   - run: make tests
